version: "3"
services:
  analyzer:
    container_name: analyzer
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - "./:/code"
    ports:
      - "8888:8888" #Debug